# Generated by Django 4.2.30 on 2026-05-10 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος Έργου')),
                ('client_name', models.CharField(max_length=200, verbose_name='Πελάτης')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('status', models.CharField(choices=[('NEW', 'Νέα Αίτηση'), ('DOCS_CHECK', 'Έλεγχος Δικαιολογητικών'), ('ASSIGNED', 'Ανατέθηκε / Προς Εκτέλεση'), ('IN_PROGRESS', 'Σε Εξέλιξη (Τεχνικό Έργο)'), ('TECH_DONE', 'Ολοκλήρωση Τεχνικού Έργου'), ('CLOSED', 'Ολοκληρώθηκε')], default='NEW', max_length=20, verbose_name='Κατάσταση')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ανατέθηκε σε')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Αρχείο')),
                ('doc_type', models.CharField(choices=[('INITIAL', 'Αρχικό Δικαιολογητικό (Γραμματεία)'), ('FINAL', 'Τελικό / Τεχνική Αναφορά (Τεχνικός)')], default='INITIAL', max_length=10, verbose_name='Τύπος Εγγράφου')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ανέβηκε από')),
            ],
        ),
    ]
