# Generated by Django 4.2.30 on 2026-05-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Οδηγίες προς Τεχνικό'),
        ),
    ]
