# Generated by Django 4.2.30 on 2026-05-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Προθεσμία Παράδοσης'),
        ),
    ]
