# Generated by Django 4.2.30 on 2026-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Διεύθυνση Έργου'),
        ),
    ]
